version: "3"

services:
  ceph:
    hostname: test
    privileged: true
    image: quay.io/ceph/demo:${CEPH_DEMO_TAG:-main-985bb83-main-centos-arm64-stream8-aarch64} # for ARM
    # image: quay.io/ceph/demo # alternative image not for ARM 
    command: demo
    environment:
      MON_IP: 192.168.55.2
      CEPH_PUBLIC_NETWORK: 192.168.55.0/24
      LANG: en_US.utf8
      CEPH_DEMO_UID: "someuid"
      CEPH_DEMO_ACCESS_KEY: "somekey"
      CEPH_DEMO_SECRET_KEY: "somesecret"
      OSD_TYPE: directory
    volumes:
      - ceph-conf:/etc/ceph
    networks:
      ceph-net:
        ipv4_address: "192.168.55.2"
  api:
    depends_on:
      - ceph
    deploy:
      restart_policy:
        condition: on-failure
        max_attempts: 5
    volumes:
      - ceph-conf:/etc/ceph
    networks:
      ceph-net:
        ipv4_address: "192.168.55.3"
    build:
      context: .
    ports:
      - "9969:9969" # expose ceph api to host
    environment:
      CFG_APP_CREATEADMIN: "true"
      CFG_APP_ADMINUSERNAME: "admin"
      CFG_APP_ADMINPASSWORD: "yoursecretpass"

volumes:
  # volume to share ceph creds between services
  ceph-conf:
    driver: local
    driver_opts:
      o: "size=128m,uid=1000"
      device: tmpfs
      type: tmpfs
    # driver: local
    # driver_opts:
    #   type: none
    #   o: bind
    #   device: ${PWD}/ceph_conf/ 
networks:
  ceph-net:
    ipam:
      driver: default
      config:
        - subnet: 192.168.55.0/24
