apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "ceph-api.fullname" . }}
  labels:
    {{- include "ceph-api.labels" . | nindent 4 }}
data:
  config: |-     
  {{- .Values.config | toYaml | nindent 4 }}
