apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ceph-api.fullname" . }}
  labels:
    {{- include "ceph-api.labels" . | nindent 4 }}
type: Opaque
data:
  config: {{ .Values.secretConfig | toYaml | b64enc | quote }}
