syntax = "proto3";

import "google/protobuf/empty.proto";

option go_package = "github.com/clyso/ceph-api/api/ceph;pb";

package ceph;

service Pool {
  rpc CreatePool (CreatePoolRequest) returns (google.protobuf.Empty) {}
}

message CreatePoolRequest {
  string pool = 1;
  optional int32 pg_num = 2;
  string pool_type = 3;
  optional string erasure_code_profile = 4;
  optional string rule_name = 5;
  optional string flags = 6;
  repeated string application_metadata = 7;
  map<string, string> configuration = 8;
  optional bool rbd_mirroring = 9;
  map<string, string> options = 10;
}
